baseURL = "https://siam-ukie.github.io"
theme = "ananke"
languageCode = "en-gb"
title = "SIAM UKIE Section"

[markup]
  [markup.goldmark]
    renderer = { unsafe = true }

[params]
  mainSections = "none"
  custom_css = ["overwrite.css", "custom.css"]
  text_color = "#000000"
  author = "SIAM UKIE Section"
  site_logo = "images/logo.png"
  logo = "images/logo.png"
  # background_color_class = "bg-dark-blue"
  title = "SIAM United Kingdom and Ireland Section"
  description = "This is a Section of the Society for Industrial and Applied Mathematics (SIAM)."
  copyright = "Copyright © 2024 SIAM UKIE Section"
  thesecretary = "Massimiliano Fasi"
  thesecretary_email = "m.fasi@leeds.ac.uk"

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/siam_ukie"
